services:
  app:
    build: .
    networks:
      - backend
    depends_on:
      - localstack
      - mongo
      - mongo-express
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017
      APP_LOCALSTACK_URL: http://localstack:4566
    ports:
      - "8080:8080"
  localstack:
    image: localstack/localstack
    networks:
      - backend
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - ./src/main/resources/scripts:/etc/localstack/init/ready.d
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    networks:
      - backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
  backend:
    driver: bridge